name: CI
on: push

env:
  DOCKER_USERNAME: ${{(secrets.DOCKER_USERNAME)}}
  DOCKER_PASSWORD: ${{(secrets.DOCKER_KEY)}}

jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
      - name: Upload app directory
        uses: actions/upload-artifact@v3
        with:
          name: app-directory
          path: src/
  Snyk-security-test:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download app directory
        uses: actions/download-artifact@v3
        with:
          name: app-directory
      - name: Run SNYK test
        run: |
          pip3 install -r requirements.txt
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  Sonar-cloud-security-test:
    runs-on: ubuntu latest
    needs: Clone-down
    steps:
      - name: Download app directory
        uses: actions/download-artifact
        with:
          name: app-directory
      - name: Run test
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Docker-image:
    needs: [Snyk-security-test, Sonar-cloud-security-test]
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
            name: code
            path: .
      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/mdp-classwork-task-1:latest .
      - name: Log in to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push image to DockerHub
        run: docker push $DOCKER_USERNAME/mdp-classwork-task-1:latest
